### ISSUE TITLE
[Bug] Kada je datum promene adrese uklonjen

### ISSUE THREAD

**Issue by srdjadzogaz** [igr/ocitana-licna-karta#1]
## Opis:

Datum promene adrese nije obavezno polje. 
Kada je prazno pravi citac izbacuje ove polje. 

## Repro:

Iz licna.txt ukloniti line 11 "adresa-datum="
### Ocekivano:
Celo polje se ne pojavljuje u generisanom fajlu
### Stvarno:
Linija postoji u generisanom fajlu:
_Datum promene adrese: ${adresa-datum}_

**Comment by igr** [comment]
O hvala! Napravio sam izmene da to polje bude opciono :)

Jedino nisam siguran u finalni izgled (da li treba da bude više praznog prostora u dnu dokumenta) - nemam ni jednu takvu kartu u okolinu sa kojom mogu da uporedim.

**Comment by srdjadzogaz** [comment]
> 

Da deluje ok cini mi se da ne treba vise prostora [imgur](https://imgur.com/a/ZZHoWpY)
Postoje razlike u samim poljima, moja je ocitana bas davno tako da moguce da su menjali onaj software "Chelik". 
Mislim da je ovo sasvim ok :) 

Hvala za software super je!
